# Generated by Django 4.1.4 on 2023-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('dov', models.DateField(blank=True, db_column='DOV', null=True)),
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('compno', models.IntegerField(blank=True, db_column='COMPNO', null=True)),
                ('pname', models.CharField(blank=True, db_column='PNAME', max_length=255, null=True)),
                ('mname', models.CharField(blank=True, db_column='MNAME', max_length=255, null=True)),
                ('vname', models.CharField(blank=True, db_column='VNAME', max_length=255, null=True)),
                ('grup', models.CharField(blank=True, db_column='GRUP', max_length=255, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('wt', models.CharField(blank=True, db_column='WT', max_length=255, null=True)),
                ('hsp1', models.IntegerField(blank=True, db_column='HSP1', null=True)),
                ('hsp2', models.IntegerField(blank=True, db_column='HSP2', null=True)),
                ('hsp3', models.IntegerField(blank=True, db_column='HSP3', null=True)),
                ('hsp4', models.IntegerField(blank=True, db_column='HSP4', null=True)),
                ('hsp5', models.IntegerField(blank=True, db_column='HSP5', null=True)),
                ('hsp6', models.IntegerField(blank=True, db_column='HSP6', null=True)),
                ('hsp7', models.IntegerField(blank=True, db_column='HSP7', null=True)),
                ('hsp8', models.IntegerField(blank=True, db_column='HSP8', null=True)),
                ('hsp9', models.IntegerField(blank=True, db_column='HSP9', null=True)),
                ('hsp10', models.IntegerField(blank=True, db_column='HSP10', null=True)),
                ('hsp11', models.IntegerField(blank=True, db_column='HSP11', null=True)),
                ('hsp12', models.IntegerField(blank=True, db_column='HSP12', null=True)),
                ('hsp13', models.IntegerField(blank=True, db_column='HSP13', null=True)),
                ('hsp14', models.IntegerField(blank=True, db_column='HSP14', null=True)),
                ('doa', models.DateField(blank=True, db_column='DOA', null=True)),
                ('doop', models.DateField(blank=True, db_column='DOOP', null=True)),
                ('time', models.TimeField(blank=True, db_column='TIME', null=True)),
                ('hhosp', models.CharField(blank=True, db_column='HHOSP', max_length=255, null=True)),
                ('facloc', models.CharField(blank=True, db_column='FACLOC', max_length=255, null=True)),
                ('temp', models.FloatField(blank=True, db_column='TEMP', null=True)),
                ('rout', models.IntegerField(blank=True, db_column='ROUT', null=True)),
                ('aesi', models.IntegerField(blank=True, db_column='AESI', null=True)),
                ('mal', models.IntegerField(blank=True, db_column='MAL', null=True)),
                ('rfrm', models.IntegerField(blank=True, db_column='RFRM', null=True)),
            ],
            options={
                'db_table': 'hospitalization',
            },
        ),
        migrations.CreateModel(
            name='Visit2',
            fields=[
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=255, null=True)),
                ('compno', models.IntegerField(blank=True, db_column='COMPNO', null=True)),
                ('vname', models.CharField(blank=True, db_column='VNAME', max_length=255, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('cat', models.IntegerField(blank=True, db_column='CAT', null=True)),
                ('mpermid', models.IntegerField(blank=True, db_column='MPERMID', null=True)),
                ('cpermid', models.IntegerField(blank=True, db_column='CPERMID', null=True)),
                ('ccnum', models.IntegerField(blank=True, db_column='CCNUM', null=True)),
                ('ccdate', models.DateField(blank=True, db_column='CCDATE', null=True)),
                ('sdov', models.DateField(blank=True, db_column='SDOV', null=True)),
                ('seen', models.CharField(blank=True, db_column='SEEN', max_length=255, null=True)),
                ('dor', models.DateField(blank=True, db_column='DOR', null=True)),
                ('reason', models.IntegerField(blank=True, db_column='REASON', null=True)),
                ('disconti', models.IntegerField(blank=True, db_column='DISCONTI', null=True)),
                ('precon', models.IntegerField(blank=True, db_column='PRECON', null=True)),
            ],
            options={
                'db_table': 'visit2',
            },
        ),
    ]
